// ==============================
// Product Interfaces
// ==============================

/**
 * Represents a product in the system.
 */
export interface ProductProps {
  id: string | number; // Unique identifier for the product.
  name: string; // Name of the product.
  price: number; // Price of the product.
  description: string; // Description of the product.
  image: string; // URL of the product image.
  category: string; // Category to which the product belongs.
  rating: number; // Average rating of the product.
  availability: 'In Stock' | 'Low Stock' | 'Out of Stock'; // Availability status of the product.
}

/**
 * Represents an order containing products.
 */
export interface ProductOrder {
  id: string; // Unique identifier for the order.
  date: string; // Date when the order was placed.
  items: number; // Number of items in the order.
  total: number; // Total cost of the order.
  status: 'pending' | 'processing' | 'shipped' | 'delivered'; // Current status of the order.
}

/**
 * Represents a recommended product for users.
 */
export interface RecommendedProduct {
  id: string; // Unique identifier for the recommended product.
  name: string; // Name of the recommended product.
  price: number; // Price of the recommended product.
  image: string; // URL of the recommended product image.
}

/**
 * Represents statistics for a product.
 */
export interface ProductStat {
  id: string; // Unique identifier for the product.
  name: string; // Name of the product.
  sold: number; // Number of units sold.
  revenue: number; // Total revenue generated by the product.
}
